### ISSUE TITLE
System.DirectoryServices.DirectoryServicesCOMException (0x80071392)

### ISSUE THREAD

**Issue by l0calh0sts** [cube0x0/noPac#3]
env :  
dc：Windows 2016 standard 
pc：Windows 10 

![图片](https://user-images.githubusercontent.com/45737471/145780656-9a3f88da-7fcf-4e21-94af-f71f6fdc59e8.png)

**Comment by l0calh0sts** [comment]
this problem has been solved

**Comment by k-fire** [comment]
> this problem has been solved

![image](https://user-images.githubusercontent.com/40354487/145786846-34111298-1eae-4272-a454-8f9dfcfe6bfd.png)

能分享下解决方法不？

**Comment by k-fire** [comment]
> > 这个问题已经解决了
> 
> ![image](https://user-images.githubusercontent.com/40354487/145786846-34111298-1eae-4272-a454-8f9dfcfe6bfd.png)
> 
> 能分享下解决方法不？

已解决
